import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { mkdir, readFile, writeFile } from 'fs/promises';
import { dirname, join, resolve, sep } from 'path';

/**
 * Where evidence files are kept. Today: a folder on the server, outside the
 * web root. A cloud drive (Google Drive, OneDrive, S3) only needs another
 * implementation of these two methods.
 */
export abstract class FileStorage {
  abstract put(key: string, data: Buffer): Promise<void>;
  abstract read(key: string): Promise<Buffer>;
}

@Injectable()
export class LocalDiskStorage extends FileStorage {
  private readonly root: string;

  constructor(config: ConfigService) {
    super();
    this.root = resolve(config.get<string>('EVIDENCE_STORAGE_DIR') || join(process.cwd(), 'storage', 'evidence'));
  }

  async put(key: string, data: Buffer) {
    const path = this.path(key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, data, { flag: 'wx' }); // never overwrite a stored record
  }

  read(key: string) {
    return readFile(this.path(key));
  }

  /** Keys are generated by the server (ids only), but never let one escape the root folder. */
  private path(key: string) {
    const path = resolve(this.root, key);
    if (!path.startsWith(this.root + sep)) throw new Error('Invalid storage key');
    return path;
  }
}
